blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/Guns-lingers/factorio-modding-tools#readme
    about: Review the project documentation.
  - name: ğŸ Bug Report
    about: Report a bug in the extension.
  - name: ğŸ’¡ Feature Request
    about: Suggest a new feature or improvement.
  - name: ğŸ“£ General Feedback
    about: Share your feedback or suggestions.
